alias functions

diff --git a/functions/adel b/functions/adel
--- a/functions/adel
+++ b/functions/adel
@@ -8,8 +8,14 @@ fi
 
 # Delete the alias from the file
 sed -i '' "/^alias $1=/d" $ZDOTDIR/conf.d/aliases.personal.zsh
+local aliastr="alias $(alias $1)"
 
 # If you want to reflect the changes immediately in your current shell, unalias the alias:
-unalias $1 2> /dev/null || echo "Alias $1 not found"
+# unalias $1 2> /dev/null || echo "Alias $1 not found"
 
-echo "Alias $1 removed from aliases.personal.zsh"
+if unalias $1 2> /dev/null; then
+    echo "Removed:"
+    echo $aliastr
+else
+    echo "Alias $1 not found"
+fi
