updates

diff --git a/functions/aliasadd b/functions/aliasadd
--- a/functions/aliasadd
+++ b/functions/aliasadd
@@ -6,6 +6,16 @@ if [ $# -lt 2 ]; then
     return 1
 fi
 
+if [ ! -f $ZDOTDIR/conf.d/aliases.personal.zsh ]; then
+  echo "Error: Alias file $ZDOTDIR/conf.d/aliases.personal.zsh does not exist" >&2
+  return 1
+fi
+
+if [ ! -w $ZDOTDIR/conf.d/aliases.personal.zsh ]; then
+  echo "Error: Alias file $ZDOTDIR/conf.d/aliases.personal.zsh is not writable" >&2
+  return 1 
+fi
+
 # Store the alias name
 alias_name="$1"
 
@@ -13,14 +23,17 @@ alias_name="$1"
 shift
 command="$*"
 
-quote_command() {
-    # Only escape single quotes
-    echo "$command" | sed "s/'/'\\\\''/g; 1s/^/'/; \$s/\$/'/"
-}
+escaped_command=$(cat <<EOF
+'$command'
+EOF
+)
 
-# Call the function
-escaped_command=$(quote_command)
+if grep -q "^alias $alias_name=" $ZDOTDIR/conf.d/aliases.personal.zsh; then
+  echo "Error: Alias $alias_name already exists" >&2
+  return 1
+fi 
 
-echo "alias $alias_name=$escaped_command" >> $ZDOTDIR/conf.d/aliases.personal.zsh
-. $ZDOTDIR/conf.d/aliases.personal.zsh
-echo "Alias $alias_name added for '$command'"
+if echo "alias $alias_name=$escaped_command" >> $ZDOTDIR/conf.d/aliases.personal.zsh; then
+  . $ZDOTDIR/conf.d/aliases.personal.zsh
+  echo "Alias $alias_name added for '$command'"
+fi
